modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="silly_eatables"
version="4.0.1"
displayName="Silly Eatables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/silly_eatables"
credits="https://github.com/Classics-Craftworks/Silly_Eatables/wiki/Credits"
authors="Classic36"
description="Eat things you shouldn't with these silly food recipes!"

[[dependencies.silly_eatables]]
    modId="neoforge"
    type="required"
    versionRange="[21.9.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.silly_eatables]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.9,1.21.10]"
    ordering="AFTER"
    side="BOTH"